# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "virtio_scsi" "xhci_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/58347df6-f1b8-4722-9554-5b9db09d9d16";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/499c3c66-70cd-4a69-8fdb-1992b9ebffbf"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens3.useDHCP = lib.mkDefault true;
  networking.interfaces.ens3.ipv4.addresses = 
    [ 
      {
        address = "178.254.30.169";
        prefixLength = 32;        
      }
    ];
  networking.defaultGateway.address = "178.254.28.1";
  networking.defaultGateway.interface = "ens3";
  networking.nameservers = 
    [ 
        "178.254.16.151"
        "178.254.16.141"
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
