# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7d0025d0-6f07-4a7d-9f5e-5954e9589365";
      fsType = "ext4";
    };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f7829663-df5c-46aa-88bf-8f3159debb33"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;
  networking = {
    interfaces.eth0.ipv4.addresses = [
      { address = "194.62.29.34"; prefixLength = 24; }
    ];
    defaultGateway = {
      address = "194.62.29.1";
      interface = "eth0";
    };
    nameservers = ["1.1.1.1" "8.8.8.8"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
